In [30]:
from csv import DictReader
from numpy import zeros
import sys
import pickle
import numpy as np

# Problem 1

In [141]:
vocab = {}
vocab_size = 0
examples = []
with open('reviews_tr.csv', 'r') as f:
    reader = DictReader(f)
    for row in reader:
        label = row['rating'] == '1'
        words = row['text'].split(' ')
        for word in words:
            if word not in vocab:
                vocab[word] = vocab_size
                vocab_size += 1
        examples.append((label, [vocab[word] for word in words]))

In [146]:
vocab

{'nice': 0,
 'food': 1,
 'especially': 2,
 'the': 3,
 'general': 4,
 'tao': 5,
 'chicken': 6,
 'and': 7,
 'shrimp': 8,
 'staff': 9,
 'is': 10,
 'courteous': 11,
 'accommodates': 12,
 'requests': 13,
 'we': 14,
 'went': 15,
 'in': 16,
 'on': 17,
 'a': 18,
 'sunday': 19,
 'evening': 20,
 'it': 21,
 'was': 22,
 'not': 23,
 'crowded': 24,
 'good': 25,
 'place': 26,
 'to': 27,
 'eat': 28,
 'were': 29,
 '4': 30,
 'of': 31,
 'us': 32,
 'costed': 33,
 'about': 34,
 '100': 35,
 'cad': 36,
 'with': 37,
 'tips': 38,
 'decent': 39,
 'but': 40,
 'overrated': 41,
 'had': 42,
 '5': 43,
 'pies': 44,
 'most': 45,
 'too': 46,
 'salty': 47,
 'tired': 48,
 'them': 49,
 'after': 50,
 '3': 51,
 'bites': 52,
 'each': 53,
 'all': 54,
 'this': 55,
 'hour': 56,
 'wait': 57,
 'crust': 58,
 'similarly': 59,
 'styled': 60,
 'pizzeria': 61,
 'mozza': 62,
 'los': 63,
 'angeles': 64,
 'better': 65,
 'they': 66,
 'are': 67,
 'known': 68,
 'for': 69,
 'their': 70,
 'fish': 71,
 'fry': 72,
 'i': 73,
 'wasn': 74,
 't': 7

In [16]:
# get bag of words representation
# should not be used explicitly

def bag_of_words_rep(word_ids, dim):
    bow_vector = zeros(dim) # creates a numpy.ndarray of shape (dim,) 
    for word_id in word_ids:
        bow_vector[word_id] += 1
    return bow_vector

In [14]:
first_bow_vector = bag_of_words_rep(examples[0][1], vocab_size)

print('memory required for examples:', sys.getsizeof(examples))
print('(estimate of) memory required for bag-of-words representation:', len(examples) * sys.getsizeof(first_bow_vector))

memory required for examples: 8448728
(estimate of) memory required for bag-of-words representation: 1659544000000


In [124]:
examples

[(True,
  [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   7,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   7,
   21,
   22,
   23,
   24,
   18,
   25,
   26,
   27,
   28,
   14,
   29,
   30,
   31,
   32,
   7,
   21,
   33,
   34,
   35,
   36,
   37,
   38]),
 (False,
  [39,
   40,
   41,
   42,
   43,
   44,
   45,
   29,
   46,
   47,
   22,
   48,
   31,
   49,
   50,
   51,
   52,
   31,
   53,
   54,
   55,
   50,
   18,
   30,
   56,
   57,
   58,
   22,
   39,
   40,
   59,
   60,
   61,
   62,
   16,
   63,
   64,
   10,
   65]),
 (False,
  [66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   3,
   77,
   78,
   65,
   71,
   72,
   16,
   79,
   80,
   81,
   66,
   82,
   83,
   27,
   84,
   18,
   85,
   86,
   87,
   31,
   85,
   88,
   89,
   90,
   91,
   92,
   54,
   93,
   94,
   21,
   95,
   96,
   97,
   98,
   10,
   99,
   23,
   100]),
 (True,
  [101,
   102,
   103,
   104,
   105,
  

In [19]:
first_bow_vector

array([1., 1., 1., ..., 0., 0., 0.])

In [131]:
# initialization
w = np.zeros(vocab_size)

# perceptron algo
n = len(examples)
for i in range(n):
    # get the classfication result of w_(i-1)
    yi = 0
    for idx in examples[i][1]:
        yi += w[idx]
    if yi > 0: # classfied True
        if examples[i][0] == False:
            for j in examples[i][1]:
                w[j] -= 1
    else:
        if examples[i][0] == True:
            for j in examples[i][1]:
                w[j] += 1

# get w
w

array([  8., -12.,  -7., ...,   0.,   0.,   0.])

In [133]:
unique, counts = np.unique(w, return_counts=True)
dict(zip(unique, counts))

{-191.0: 1,
 -189.0: 1,
 -157.0: 1,
 -154.0: 1,
 -152.0: 3,
 -151.0: 1,
 -150.0: 2,
 -149.0: 2,
 -146.0: 1,
 -144.0: 2,
 -141.0: 2,
 -140.0: 1,
 -136.0: 2,
 -131.0: 1,
 -125.0: 1,
 -124.0: 1,
 -121.0: 3,
 -117.0: 1,
 -116.0: 1,
 -115.0: 1,
 -113.0: 1,
 -111.0: 2,
 -110.0: 1,
 -109.0: 2,
 -107.0: 1,
 -105.0: 1,
 -104.0: 1,
 -103.0: 3,
 -102.0: 1,
 -101.0: 1,
 -99.0: 1,
 -98.0: 1,
 -97.0: 4,
 -96.0: 1,
 -95.0: 1,
 -94.0: 1,
 -91.0: 2,
 -90.0: 2,
 -89.0: 1,
 -88.0: 1,
 -87.0: 2,
 -83.0: 2,
 -82.0: 1,
 -81.0: 2,
 -80.0: 1,
 -79.0: 1,
 -77.0: 6,
 -76.0: 2,
 -75.0: 2,
 -74.0: 2,
 -72.0: 2,
 -71.0: 5,
 -70.0: 1,
 -69.0: 2,
 -68.0: 6,
 -67.0: 1,
 -66.0: 2,
 -65.0: 5,
 -64.0: 6,
 -63.0: 3,
 -62.0: 8,
 -61.0: 5,
 -60.0: 7,
 -59.0: 13,
 -58.0: 4,
 -57.0: 4,
 -56.0: 12,
 -55.0: 8,
 -54.0: 8,
 -53.0: 6,
 -52.0: 6,
 -51.0: 12,
 -50.0: 5,
 -49.0: 12,
 -48.0: 13,
 -47.0: 4,
 -46.0: 13,
 -45.0: 12,
 -44.0: 15,
 -43.0: 10,
 -42.0: 18,
 -41.0: 21,
 -40.0: 10,
 -39.0: 16,
 -38.0: 17,
 -37.0: 18,
 -36.0: 2

In [240]:
# calculate training error rate
n = len(examples)
train_wrong = 0
for i in range(n):
    yi = 0
    for idx in examples[i][1]:
        yi += w[idx]
    if yi > 0: # classfied True
        if examples[i][0] == False:
            train_wrong += 1
    else:
        if examples[i][0] == True:
            train_wrong += 1
            
print(train_wrong/n)

0.179362


In [230]:
te_vocab = dict(vocab)
te_vocab_size = vocab_size
te_examples = []
with open('reviews_te.csv', 'r') as f:
    reader = DictReader(f)
    for row in reader:
        label = row['rating'] == '1'
        words = row['text'].split(' ')
        for word in words:
            if word not in te_vocab:
                te_vocab[word] = te_vocab_size
                te_vocab_size += 1
        te_examples.append((label, [te_vocab[word] for word in words]))

In [243]:
# calculate test error rate
te_n = len(te_examples)
test_wrong = 0

pad_w = np.zeros(te_vocab_size - vocab_size)
w_updated = np.hstack((w, pad_w))

for i in range(te_n):
    yi = 0
    for idx in te_examples[i][1]:
        yi += w_updated[idx]
    if yi > 0: # classfied True
        if te_examples[i][0] == False:
            test_wrong += 1
    else:
        if te_examples[i][0] == True:
            test_wrong += 1
            
print(test_wrong/te_n)

0.1799907535252185


# Problem 2

In [149]:
most_pos = [165.0, 154.0, 144.0, 133.0, 129.0, 128.0, 120.0, 119.0, 117.0, 114.0]
most_neg = [-191.0, -189.0, -157.0, -154.0, -152.0, -151.0, -150.0, -149.0, -146.0, -144.0]
indices_pos = np.where(np.isin(w, most_pos))
indices_neg = np.where(np.isin(w, most_neg))

In [151]:
print(indices_pos)
print(indices_neg)

(array([ 101,  793,  832, 1139, 1334, 1628, 1692, 2289, 2956, 3008, 4342]),)
(array([ 244,  913,  939,  961, 1199, 1218, 1343, 1722, 1957, 2266, 2288,
       2609, 2820, 4540, 4865]),)


In [152]:
inv_vocab = {v: k for k, v in vocab.items()}
inv_vocab

{0: 'nice',
 1: 'food',
 2: 'especially',
 3: 'the',
 4: 'general',
 5: 'tao',
 6: 'chicken',
 7: 'and',
 8: 'shrimp',
 9: 'staff',
 10: 'is',
 11: 'courteous',
 12: 'accommodates',
 13: 'requests',
 14: 'we',
 15: 'went',
 16: 'in',
 17: 'on',
 18: 'a',
 19: 'sunday',
 20: 'evening',
 21: 'it',
 22: 'was',
 23: 'not',
 24: 'crowded',
 25: 'good',
 26: 'place',
 27: 'to',
 28: 'eat',
 29: 'were',
 30: '4',
 31: 'of',
 32: 'us',
 33: 'costed',
 34: 'about',
 35: '100',
 36: 'cad',
 37: 'with',
 38: 'tips',
 39: 'decent',
 40: 'but',
 41: 'overrated',
 42: 'had',
 43: '5',
 44: 'pies',
 45: 'most',
 46: 'too',
 47: 'salty',
 48: 'tired',
 49: 'them',
 50: 'after',
 51: '3',
 52: 'bites',
 53: 'each',
 54: 'all',
 55: 'this',
 56: 'hour',
 57: 'wait',
 58: 'crust',
 59: 'similarly',
 60: 'styled',
 61: 'pizzeria',
 62: 'mozza',
 63: 'los',
 64: 'angeles',
 65: 'better',
 66: 'they',
 67: 'are',
 68: 'known',
 69: 'for',
 70: 'their',
 71: 'fish',
 72: 'fry',
 73: 'i',
 74: 'wasn',
 75: 't

In [158]:
pos_words = []
neg_words = []

for i in indices_pos[0]:
    pos_words.append(inv_vocab[i])

for i in indices_neg[0]:
    neg_words.append(inv_vocab[i])

print(pos_words)
print(neg_words)

['fantastic', 'perfect', 'perfection', 'heaven', 'phenomenal', 'perfectly', 'disappoint', 'superb', 'incredible', 'gem', 'skeptical']
['worst', 'poisoning', 'inedible', 'disgusting', 'disappointing', 'awful', 'flavorless', 'mediocre', 'horrible', 'underwhelmed', 'bland', 'lacked', 'worse', 'meh', 'tasteless']


# Problem 3

In [168]:
# initialization
w = np.zeros(vocab_size)
w_sum = np.zeros(vocab_size)

# perceptron algo
n = len(examples)
for i in range(n):
    # get the classfication result of w_(i-1)
    yi = 0
    for idx in examples[i][1]:
        yi += w[idx]
    if yi > 0: # classfied True
        if examples[i][0] == False:
            for j in examples[i][1]:
                w[j] -= 1
    else:
        if examples[i][0] == True:
            for j in examples[i][1]:
                w[j] += 1
    w_sum = np.add(w, w_sum)

# get w
w

array([  8., -12.,  -7., ...,   0.,   0.,   0.])

In [169]:
w_sum

array([13755062., -5602263.,  3017775., ...,        0.,        0.,
              0.])

In [170]:
w_avg = [x / n for x in w_sum]
w_avg

[13.755062,
 -5.602263,
 3.017775,
 -1.053236,
 6.050461,
 -6.454475,
 0.366318,
 7.141983,
 -5.534767,
 -3.02465,
 1.975915,
 25.699092,
 3.228955,
 4.69592,
 7.622521,
 -3.08721,
 1.772846,
 -0.591519,
 0.992292,
 7.491767,
 -2.592576,
 3.815479,
 -8.606555,
 -43.313506,
 9.790182,
 19.127745,
 2.022545,
 -4.642311,
 5.690129,
 -12.492797,
 41.513011,
 -0.129836,
 5.660077,
 0.56407,
 6.29763,
 5.611669,
 3.420168,
 4.984152,
 -7.063481,
 -61.114837,
 -11.275244,
 -79.442358,
 0.719368,
 38.94581,
 -3.280515,
 15.180595,
 6.556953,
 -64.530117,
 -10.923325,
 0.993972,
 -11.228185,
 -48.217204,
 -40.770615,
 16.626834,
 8.784713,
 2.358339,
 -40.329621,
 26.204231,
 1.950926,
 -18.426648,
 7.466195,
 -1.936387,
 -3.91537,
 2.381135,
 -1.670493,
 -30.788924,
 1.907203,
 -4.018265,
 -11.594931,
 -4.856492,
 -1.788922,
 -0.315096,
 -1.415496,
 6.779142,
 -47.338855,
 -9.00439,
 13.631417,
 -14.296473,
 -0.687929,
 -2.027648,
 -11.326323,
 -51.293309,
 6.781694,
 -5.496264,
 2.676521,
 25

In [178]:
unique, counts = np.unique(w_avg, return_counts=True)
my_dict = dict(zip(unique, counts))

# Convert the dictionary to a list of key-value tuples and slice it
last_items = list(my_dict.items())[-10:]
first_items = list(my_dict.items())[:10]

# Convert the list back to a dictionary
last_dict = dict(last_items)
first_dict = dict(first_items)
print(last_dict, first_dict)

{100.345422: 1, 101.886822: 1, 102.296707: 1, 102.322016: 1, 104.747131: 1, 105.548045: 1, 111.589897: 1, 111.864248: 1, 120.319817: 1, 120.832504: 1} {-176.515287: 1, -162.862538: 1, -150.722627: 1, -137.975265: 1, -130.601575: 1, -130.107949: 1, -127.439149: 1, -123.798148: 1, -123.298077: 1, -122.248706: 1}


In [171]:
# calculate training error rate
n = len(examples)
avg_train_wrong = 0
for i in range(n):
    yi = 0
    for idx in examples[i][1]:
        yi += w_avg[idx]
    if yi > 0: # classfied True
        if examples[i][0] == False:
            avg_train_wrong += 1
    else:
        if examples[i][0] == True:
            avg_train_wrong += 1
            
avg_train_wrong/n

0.104435

In [244]:
# calculate test error rate
te_n = len(te_examples)
avg_test_wrong = 0

w_avg_updated = np.hstack((w_avg, pad_w))

for i in range(te_n):
    yi = 0
    for idx in te_examples[i][1]:
        yi += w_avg_updated[idx]
    if yi > 0: # classfied True
        if te_examples[i][0] == False:
            avg_test_wrong += 1
    else:
        if te_examples[i][0] == True:
            avg_test_wrong += 1
            
print(avg_test_wrong/te_n)

0.10665621231905337


In [180]:
avg_most_pos = [100.345422, 101.886822, 102.296707, 102.322016, 104.747131, 105.548045, 111.589897, 111.864248, 120.319817, 120.832504]
avg_most_neg = [-176.515287, -162.862538, -150.722627, -137.975265, -130.601575, -130.107949, -127.439149, -123.798148, -123.298077, -122.248706]
avg_indices_pos = np.where(np.isin(w_avg, avg_most_pos))
avg_indices_neg = np.where(np.isin(w_avg, avg_most_neg))

In [181]:
avg_pos_words = []
avg_neg_words = []

for i in avg_indices_pos[0]:
    avg_pos_words.append(inv_vocab[i])

for i in avg_indices_neg[0]:
    avg_neg_words.append(inv_vocab[i])

print(avg_pos_words)
print(avg_neg_words)

['fantastic', 'excellent', 'delicious', 'amazing', 'perfect', 'perfection', 'perfectly', 'disappoint', 'incredible', 'gem']
['worst', 'terrible', 'disappointing', 'awful', 'mediocre', 'horrible', 'bland', 'lacked', 'disappointment', 'meh']


# Problem 4

In [63]:
freedman = pickle.load(open('freedman.pkl', 'rb'))

In [252]:
n = freedman['data'].shape[0]
d = freedman['data'].shape[1]

In [249]:
freedman

{'data': array([[ 0.49671415, -0.1382643 ,  0.64768854, ...,  0.64084286,
         -0.57117899,  0.57258278],
        [ 1.39935544,  0.92463368,  0.05963037, ..., -0.88187465,
         -0.16306696, -0.74490264],
        [-0.67517827, -0.14451867, -0.79241992, ..., -1.24176058,
          0.33417642, -0.15525905],
        ...,
        [ 1.74231559, -0.10577995, -0.06978952, ...,  0.26110412,
         -2.24801252,  0.48971934],
        [-0.30113951, -0.5932052 ,  1.47012983, ..., -0.14989653,
         -0.45810025, -0.45389854],
        [ 1.35609217, -0.5400079 , -0.03089371, ...,  0.40918508,
         -0.21109167,  0.12006294]]),
 'labels': array([ 1.03059459e+00, -1.15535477e+00,  5.75437190e-01, -6.19238458e-01,
        -3.27402806e-01,  4.76042669e-02, -1.19491052e-01, -1.67610564e+00,
         1.38181202e+00,  1.13440922e+00, -1.46316493e-01,  9.34398627e-01,
        -3.97695161e-01, -9.82197444e-01,  5.44130142e-02, -1.16890286e+00,
         6.09050623e-01, -7.02562749e-01, -1.600030

In [260]:
##################################################
# part (a)
##################################################

# make deep copies of the data
X = np.array(freedman['data'])
Y = np.array(freedman['labels'])
P = np.zeros(d)

# calculate p_j values
for j in range(d):
    idx = slice(j, j+1)
    Xj = X[:, idx].reshape(100,)
    P[j] = Xj @ Y / n

# get indices of relavant features
threshold = 2/np.sqrt(n)
J = P[abs(P)>threshold]
print("Number of features in J is " + str(J.shape[0]))

Number of features in J is 42


In [262]:
##################################################
# part (b)
##################################################

# filter out irrelavant features
indices = np.where(np.isin(P, J))[0]
data = X[:, indices]

# get the weight vector
def learn(train_x, train_y):
    return np.linalg.pinv(train_x).dot(train_y)

shortw = learn(data, Y)

# pad this weight vector
w = np.zeros(d)
w[indices] = shortw

# calculate sse
sse = ((X @ w - Y)**2).sum()/n
print(sse)

0.20727664942631852


In [291]:
##################################################
# part (c)
##################################################

# make deep copies of the data
testdata = np.array(freedman['testdata'])
testlabels = np.array(freedman['testlabels'])

Yhead = testdata.dot(w)

# calculate sse on test dataset
testsse = np.mean(((Yhead - testlabels)**2))
print(testsse)  # 1.447168408563264

1.447168408563264


In [300]:
##################################################
# part (e)
##################################################

# make deep copies of the data
X2 = np.array(freedman['data2'])
Y2 = np.array(freedman['labels2'])

# filter out irrelavant features
data2 = X2[:, indices]

# get the weight vector
def learn(train_x, train_y):
    return np.linalg.pinv(train_x).dot(train_y)

shortw2 = learn(data2, Y2)

# pad this weight vector
w2 = np.zeros(d)
w2[indices] = shortw2

# calculate sse
sse2 = np.mean(((X2 @ w2 - Y2)**2))
print(sse2)

0.6008415658067544
