# hw0

In [1]:
import numpy as np

## 23 extract odd integers
write a function that returns a numpy array containing all odd integers from a given numpy array $x$ of numbers

In [11]:
def extract_odd_numbers(x):
    result = np.array([])
    for num in x:
        if(num % 2 != 0):
            result = np.append(result, num)
    return result

In [12]:
test = np.array([1,2,3,4,5])
print(extract_odd_numbers(test))

[1. 3. 5.]


## 24 construct matrix
given a positive integer, returns a $n*n$ numpy array with the first column being all ones, the second column being all twos and so on.

In [71]:
def make_funny_matrix(n):
    result = np.empty([n, n])
    for i in range(n):
        for j in range(n):
            result[i][j]=j+1
    return result

In [72]:
print(make_funny_matrix(5))

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


## 25 append column
returns an $m*(n+1)$ numpy array that appends a column of all ones to the end of a given $m*n$ array A

In [95]:
def append_column(A):
    col = np.ones(A.shape[0]).reshape(3,1)
    return np.hstack((A, col))

In [96]:
A = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(A)
print(append_column(A))

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1. 2. 3. 4. 5. 1.]
 [1. 2. 3. 4. 5. 1.]
 [1. 2. 3. 4. 5. 1.]]
